name: Test Reports Workflow

on:
#   push:
#     branches:
#       - main
    workflow_dispatch:
    workflow_call:

jobs:
  test_reports_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven 

    - name: Build and Test
      run: |
        mvn compile
        mvn test
        mvn clean package -DskipTests=true

    - name: Publish Test Results
      if: always()
      run: |
        mkdir -p test-reports
        cp -r target/surefire-reports test-reports
        ls -R test-reports
        echo "::set-output name=report-path::test-reports"

    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: test-reports
