name: Deploy in ECR

on:
#   push:
#     branches:
#       - main
    workflow_dispatch:
     inputs:
      username:
         description: "Username"
         required: true
         default: "nandhini1999"
      password:
         description: "Password"
         required: true
         default: "Nandhini_99"
  

jobs:
  pull-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}

      - name: Pull Docker image
        run: docker pull papannah/githubactions:master

      - name: Tag Docker image
        run: |
         aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 215099615090.dkr.ecr.us-east-1.amazonaws.com
         docker tag papannah/githubactions:master 215099615090.dkr.ecr.us-east-1.amazonaws.com/demo:latest
#         aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 215099615090.dkr.ecr.us-east-1.amazonaws.com
#         docker tag nandhini1999/sample:latest 215099615090.dkr.ecr.us-east-1.amazonaws.com/demo:latest

      - name: Push Docker image to ECR
        run: docker push 215099615090.dkr.ecr.us-east-1.amazonaws.com/demo:latest
#         run: docker push public.ecr.aws/f4w6n6b1/my-ecr-repo:latest
        
         
