name: "Setup Docker"
on:
  workflow_dispatch:
#   workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
      setup:
        required: false
        type: string
        default: ""
      working_directory:
        required: false
        type: string
        default: "."
      username:
         description: "Username"
         required: true
         default: "nandhini1999"
      password:
         description: "Password"
         required: true
         default: "Nandhini_99"
 

jobs:
  build:
    defaults:
      run:
        working-directory: ${{inputs.working_directory}}

    runs-on: ${{inputs.runs_on}}
    
#   using: "composite"

    steps:
   
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        
#     - name: Build docker image
#       run: |
#        docker build . --file Dockerfile --tag my-app:latest

    - name: Login to DockerHub
#       if: ${{ github.event_name == 'release' || github.event_name == 'push' && github.ref == 'refs/heads/master' && inputs.password != ''  }}
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        
#     - name: Push the docker image
#       run: |
#        docker tag my-app:latest nandhini1999/sample:latest 
#        docker push nandhini1999/sample:latest
       
    - name: Run container
      run: |
        docker run nandhini1999/sample:latest


