name: "Setup Docker"
on:
  workflow_dispatch:
#   workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
      setup:
        required: false
        type: string
        default: ""
      working_directory:
        required: false
        type: string
        default: "."
      username:
         description: "Username"
         required: true
      password:
         description: "Password"
         required: true
 
#   ghcr_username:
#     description: "GHCR username. Usually set from the github.actor variable"
#     required: true
#   ghcr_password:
#     description: "GHCR password. Usually set from the secrets.GITHUB_TOKEN variable"
#     required: true

jobs:
  build:
    defaults:
      run:
        working-directory: ${{inputs.working_directory}}

    runs-on: ${{inputs.runs_on}}
    
#   using: "composite"

    steps:
    
#     - name: Get Short SHA
#       id: vars
#       run: |
#         echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_ENV
#       shell: bash

#     - name: Set up QEMU
#       uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Login to DockerHub
#       if: ${{ github.event_name == 'release' || github.event_name == 'push' && github.ref == 'refs/heads/master' && inputs.password != ''  }}
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

#     - name: Login to GitHub Container Registry
# #       if: ${{ github.event_name == 'release' || github.event_name == 'push' && github.ref == 'refs/heads/master' && inputs.ghcr_password != ''  }}
#       uses: docker/login-action@v2
#       with:
#         registry: ghcr.io
#         username: ${{ inputs.ghcr_username }}
#         password: ${{ inputs.ghcr_password }}
