name: JFrog Setup
on:
  workflow_dispatch:
#   workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
      setup:
        required: false
        type: string
        default: ""
      working_directory:
        required: false
        type: string
        default: "."
        

jobs:
  build:
    defaults:
      run:
        working-directory: ${{inputs.working_directory}}

    runs-on: ${{inputs.runs_on}}
    
#   using: "composite"

    steps:
   
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up jfrog
      uses: jfrog/setup-jfrog-cli@v3
      with:
        version: latest
        
    - name: URL check
      uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: https://jfrog.phvr.co.in
        JF_USER: admin
        JF_PASSWORD: Admin@123

    
    # Basic authentication credentials
#         JF_URL: ${{ secrets.JF_URL }}
#         JF_USER: ${{ secrets.JF_USER }}
#         JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
#     or
#     # JFrog Platform access token
#     JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

            
        
    - name: Jfrog version
      run: |
       jf --version
       jf rt ping
       
    - name: artifact
      uses: ./.github/workflows/package.yml
      with:
        package-goal: 'clean package -DskipTests=true'
       
    - name: Publish JAR artifact to Artifactory
      run: |
        jfrog rt u target/*.jar https://jfrog.phvr.co.in/artifactory/demo-maven/demo.jar --url=https://jfrog.phvr.co.in --user=admin --password=Admin@123

