name: Jira Integration
on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

jobs:
  jira_integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
#       - name: Install dependencies
#         run: npm install
        
      - name: Trigger Jira integration
        run: |
          curl --location --request POST 'https://your-jira-instance.com/rest/api/2/issue/{issueKey}/transitions' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: ${{ secrets.JIRA_API_TOKEN }}' \
          --data-raw '{
            "transition": {
              "id": "YOUR_TRANSITION_ID"
            }
          }'
