name: JAVA

on:
  push:
    branches:
      - master

jobs:
  maven-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        uses: ./.github/workflows/maven-goals.yml
        with:
          GOAL: '-B -DskipTests clean package'

  maven-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        uses: ./.github/workflows/maven-goals.yml
        with:
          GOAL: 'test'

#   maven-coverage:
#     uses: ./.github/workflows/maven-goals.yml
#     with:
#       GOAL: 'jacoco:report'


#   build:
#     needs: [maven-build, maven-test]

#     runs-on: ubuntu-latest

#     steps:
#       - name: Check
#         run: echo 'Success'
