name: Reusable Workflow

on:
  workflow_dispatch:
  
jobs:
  call-workflow:
      runs-on: ubuntu-latest
      steps:
        - name: Execute Maven Goals
          uses: ./.github/workflows/maven-goals.yml
          with:
            GOAL: '-B -DskipTests clean package'
          
        - name: Execute Unit test
          uses: ./.github/workflows/unitTest-coverage.yml
