name: JAVA

on:
  push:
    branches:
      - master

jobs:
  maven-compile-test:
    uses: ./.github/workflows/maven-goals.yml
    with:
      GOAL1: '-B -DskipTests clean package'
      GOAL2: 'test'


  build:
    needs: [maven-compile-test]

    runs-on: ubuntu-latest

    steps:
      - name: Check
        run: echo 'Success'
