name: JAVA- CD

on:
#   push:
#     branches:
#       - main
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/sequence.yml
    
#   docker-build_push:
#     needs: check
#     uses: ./.github/workflows/docker.yml
#     with:
#       username: 'nandhini1999'
#       password: 'Nandhini_99'
      
  push-to-ecr:
#     needs: docker-build_push
    uses: ./.github/workflows/aws-ecr.yml

  deploy-to-ecs:
    needs: push-to-ecr
    uses: ./.github/workflows/aws-ecs.yml
