name: JAVA

on:
#   push:
#     branches:
#       - master
      
  workflow_dispatch:

jobs:
  maven-compile-test:
    uses: ./.github/workflows/maven-goals.yml
    with:
      build-goal: '-B -DskipTests clean package'
      test-goal: 'test'
      
  check:
    uses: ./.github/workflows/sequence.yml


  test:
#     uses: ./.github/workflows/maven-goals.yml
#     with:
# #       build-goal: '-B -DskipTests clean package'
#       test-goal: 'test'
      
      
    needs: [maven-compile-test]

    runs-on: ubuntu-latest

    steps:
      - name: Verify
        run: echo "Success"
        
