name: JAVA

on:
  push:
    branches:
      - main

jobs:
  verify-maven:
    uses: ./.github/workflows/maven-goals.yml
    env:
      GOAL: '-version'
      
  runs-on: ubuntu-latest
    steps:
       - name: Check
         run: echo 'Success'
