name: JAVA

on:
  push:
    branches:
      - master

jobs:
  maven-build:
    uses: ./.github/workflows/maven-goals.yml
    with:
      GOAL: '-B -DskipTests clean package'

  maven-test:
    uses: ./.github/workflows/maven-goals.yml
    with:
      GOAL: 'test'

  maven-coverage:
    uses: ./.github/workflows/maven-goals.yml
    with:
      GOAL: 'jacoco:report'


  build:
    needs: [maven-build, maven-test, maven-coverage]

    runs-on: ubuntu-latest

    steps:
      - name: Check
        run: echo 'Success'
