name: JAVA

on:
  push:
    branches:
      - master

jobs:
  verify-maven:
    uses: ./.github/workflows/maven-goals.yml
    with:
      GOAL: '-version'


  build:
    needs: [verify-maven]

    runs-on: ubuntu-latest

    steps:
      - name: Check
        run: echo 'Success'
