name: JAVA

on:
#   push:
#     branches:
#       - master
      
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/sequence.yml
    
  maven-compile:
    needs: check
    uses: ./.github/workflows/maven-build.yml
    with:
      build-goal: '-B -DskipTests clean package'
      
  maven-test:
    needs: maven-compile
    uses: ./.github/workflows/maven-test.yml
    with:
      test-goal: 'test'


  test:
#     uses: ./.github/workflows/maven-test.yml
#     with:
# #       build-goal: '-B -DskipTests clean package'
#       test-goal: 'test'
      
      
    needs: maven-test

    runs-on: ubuntu-latest

    steps:
      - name: Verify
        run: echo "Success"
        
