name: Java Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          
      - name: Build
        run: |
           mvn -B -DskipTests clean package
           
      - name: Test
        run: |
           mvn test

      - name: Publish Test Results
        if: always()
        uses: junit-team/junit-report-builder@v1
        with:
          reports: target/surefire-reports/*.xml
