name: JAVA

on:
#   push:
#     branches:
#       - master
      
  workflow_dispatch:

jobs:
  maven-compile-test:
    uses: ./.github/workflows/maven-goals.yml
    with:
      build-goal: '-B -DskipTests clean package'
      test-goal: 'test'


  build:
    needs: [maven-compile-test]

    runs-on: ubuntu-latest

    steps:
      - name: Check
        run: echo 'Success'
        
