name: Maven Workflow

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
      setup:
        required: false
        type: string
        default: ""
      working_directory:
        required: false
        type: string
        default: "."

jobs:
  build:
    defaults:
      run:
        working-directory: ${{inputs.working_directory}}

    runs-on: ${{inputs.runs_on}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 1.11  

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: 1.11  
          maven-version: 3.x  
          
      - name: Build with Maven
        run: mvn -s ${{ env.GOAL }}
