name: Sequential Workflow

on:
#   push:
#     branches:
#       - master
      
  workflow_call:

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Run Build
        run: echo "Success"
  
  
  job2:
    name: Second Job
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Run Job 2
        run: echo "Running Job 2"
  
  job3:
    name: Third Job
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Run Job 3
        run: echo "Running Job 3"


